### ISSUE TITLE
 failed to create interface wlan0

### ISSUE THREAD

**Issue by roediman** [braindead-sec/rogue-captive#2]
i got these error...
any suggestions?

hostapd.conf   failed to create interface wlan0:-95 operation not suported

**Comment by zand999** [comment]
Just to make sure, you are you using a raspberry pi with built in wifi? That is the only problem I could think of. I did not have this problem.

**Comment by braindead-sec** [comment]
If your wifi adapter is using a different interface, you'll need to replace wlan0 with the correct interface in both hostapd.conf and rc.local. Also be sure to delete any wpa_supplicant config files that automatically connect your wifi adapter to an access point (I just added this to the install script).
